/run/numberOfThreads 12 #set the number of threads

/run/initialize
/vis/open
/vis/viewer/set/viewpointVector 1 1 1
/vis/viewer/set/autoRefresh true
/vis/drawVolume
/vis/scene/endOfEventAction accumulate 1000
/vis/scene/add/scale 10 cm
/vis/scene/add/eventID
/tracking/verbose

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set proton red
/vis/modeling/trajectories/drawByParticleID-0/set e- blue
/vis/modeling/trajectories/drawByParticleID-0/set e+ magenta
/vis/modeling/trajectories/drawByParticleID-0/set gamma green
/vis/modeling/trajectories/drawByParticleID-0/set neutron gray
/vis/modeling/trajectories/drawByParticleID-0/set pi+ yellow
/vis/modeling/trajectories/drawByParticleID-0/set pi- orange
/vis/modeling/trajectories/drawByParticleID-0/set kaon+ cyan
/vis/modeling/trajectories/drawByParticleID-0/set kaon- white

/vis/scene/add/trajectories smooth
